[alias]
b = "build"
br = "build -r"
r = "run" 
rr = "run -r"
d = "doc"
do = "doc --open"
c = "check"
cl = "clean"
t = "test"
be = "bench"
# examples
rrfile = "r -r --example file_hasher"
rrreader= "r -r --example reader_hasher"
rrstdin = "r -r --example stdin_hasher"
rrstring = "r -r --example string_hasher"
rfile = "r --example file_hasher"
rreader = "r --example reader_hasher"
rstdin = "r --example stdin_hasher"
rstring = "r --example string_hasher"
brfile = "b -r --example file_hasher"
brreader = "b -r --example reader_hasher"
brstdin = "b -r --example stdin_hasher"
brstring = "b -r --example string_hasher"
bfile = "b --example file_hasher"
breader = "b --example reader_hasher"
bstdin = "b --example stdin_hasher"
bstring = "b --example string_hasher"

